CREATE TABLE IF NOT EXISTS "Semester" (
    "SemesterId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SemesterName" character varying(100) NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "Student" (
    "StudentId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "Subject" (
    "SubjectId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SubjectCode" character varying(20) NOT NULL,
    "SubjectName" character varying(100) NOT NULL,
    "Credit" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "Course" (
    "CourseId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CourseName" character varying(100) NOT NULL,
    "SemesterId" integer NOT NULL REFERENCES "Semester" ("SemesterId") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Enrollment" (
    "EnrollmentId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" integer NOT NULL REFERENCES "Student" ("StudentId") ON DELETE RESTRICT,
    "CourseId" integer NOT NULL REFERENCES "Course" ("CourseId") ON DELETE RESTRICT,
    "EnrollDate" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS "User" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username" character varying(50) NOT NULL UNIQUE,
    "PasswordHash" character varying(255) NOT NULL,
    "Role" character varying(20) NOT NULL,
    "RefreshToken" character varying(500),
    "RefreshTokenExpiry" timestamp with time zone
);

CREATE INDEX IF NOT EXISTS "IX_Course_SemesterId" ON "Course" ("SemesterId");
CREATE INDEX IF NOT EXISTS "IX_Enrollment_CourseId" ON "Enrollment" ("CourseId");
CREATE INDEX IF NOT EXISTS "IX_Enrollment_StudentId" ON "Enrollment" ("StudentId");

-- Seed default admin user  (password: Admin@123)
INSERT INTO "User" ("Username", "PasswordHash", "Role")
VALUES ('admin', '$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Admin')
ON CONFLICT DO NOTHING;
